# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created: Fri Jun 17 07:17:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWidget(object):
    def setupUi(self, MainWidget):
        MainWidget.setObjectName(_fromUtf8("MainWidget"))
        MainWidget.resize(721, 581)
        self.verticalLayout = QtGui.QVBoxLayout(MainWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(MainWidget)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitter = QtGui.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.functions = FunctionsTableWidget(self.splitter)
        self.functions.setObjectName(_fromUtf8("functions"))
        self.functions.setColumnCount(0)
        self.functions.setRowCount(0)
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget_5 = QtGui.QWidget(self.widget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_4 = QtGui.QWidget(self.widget_5)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.formLayout = QtGui.QFormLayout(self.widget_4)
        self.formLayout.setMargin(0)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.widget_2 = QtGui.QWidget(self.widget_4)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.categories = CategoryComboBox(self.widget_2)
        self.categories.setMinimumSize(QtCore.QSize(200, 0))
        self.categories.setObjectName(_fromUtf8("categories"))
        self.horizontalLayout.addWidget(self.categories)
        self.add_category = QtGui.QToolButton(self.widget_2)
        self.add_category.setAutoRaise(True)
        self.add_category.setObjectName(_fromUtf8("add_category"))
        self.horizontalLayout.addWidget(self.add_category)
        self.delete_category = QtGui.QToolButton(self.widget_2)
        self.delete_category.setAutoRaise(True)
        self.delete_category.setObjectName(_fromUtf8("delete_category"))
        self.horizontalLayout.addWidget(self.delete_category)
        self.edit_category = QtGui.QToolButton(self.widget_2)
        self.edit_category.setAutoRaise(True)
        self.edit_category.setObjectName(_fromUtf8("edit_category"))
        self.horizontalLayout.addWidget(self.edit_category)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.widget_2)
        self.label_2 = QtGui.QLabel(self.widget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.widget_3 = QtGui.QWidget(self.widget_4)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.files_edit = QtGui.QLineEdit(self.widget_3)
        self.files_edit.setMinimumSize(QtCore.QSize(200, 0))
        self.files_edit.setReadOnly(True)
        self.files_edit.setObjectName(_fromUtf8("files_edit"))
        self.horizontalLayout_2.addWidget(self.files_edit)
        self.select_files = QtGui.QToolButton(self.widget_3)
        self.select_files.setAutoRaise(True)
        self.select_files.setObjectName(_fromUtf8("select_files"))
        self.horizontalLayout_2.addWidget(self.select_files)
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.widget_3)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_6 = QtGui.QWidget(self.widget_5)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(283, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.upload_button = QtGui.QPushButton(self.widget_6)
        self.upload_button.setObjectName(_fromUtf8("upload_button"))
        self.horizontalLayout_3.addWidget(self.upload_button)
        self.verticalLayout_2.addWidget(self.widget_6)
        spacerItem1 = QtGui.QSpacerItem(20, 132, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.widget_5)
        spacerItem2 = QtGui.QSpacerItem(351, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(MainWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWidget)

    def retranslateUi(self, MainWidget):
        MainWidget.setWindowTitle(QtGui.QApplication.translate("MainWidget", "RevLib Administrator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWidget", "Category:", None, QtGui.QApplication.UnicodeUTF8))
        self.add_category.setText(QtGui.QApplication.translate("MainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_category.setText(QtGui.QApplication.translate("MainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.edit_category.setText(QtGui.QApplication.translate("MainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWidget", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.select_files.setText(QtGui.QApplication.translate("MainWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_button.setText(QtGui.QApplication.translate("MainWidget", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWidget", "Functions", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWidget", "Circuits", None, QtGui.QApplication.UnicodeUTF8))

from core.FunctionsTableWidget import FunctionsTableWidget
from core.CategoryComboBox import CategoryComboBox
