##===- lib/Transforms/ResourceAnalysis/Makefile -----------------------*- Makefile -*-===##
#
#
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = ScaffoldResourceAnalysis
LOADABLE_MODULE = 1
USEDLIBS =

include $(LEVEL)/Makefile.common

