#!/bin/bash

if [[ "$#" < 1 ]]
then
  echo "Warning: No input files given. No output produced."
  echo "Usage:   ctqg <my_circuit_name_without_extension>";
  exit 0
fi

if [ ! -e "$CTQG_PATH/convert_to_bbrl" ]
then
  echo -n "For your information: Building \"convert_to_bbrl\"                ... "
  gcc -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/ctqg________________________.c \
  $CTQG_PATH/ctqg________________sdll_sgt.c \
  $CTQG_PATH/ctqg__________memory_manager.c \
  -o $CTQG_PATH/convert_to_bbrl  
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

if [ ! -e "$CTQG_PATH/convert_to_qasm" ]
then
  echo -n "For your information: Building \"convert_to_qasm\"                ... "
  gcc -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/qasm_______compatible_output.c \
  -o $CTQG_PATH/convert_to_qasm
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

if [ ! -e "$CTQG_PATH/bbrl_lib_fixed_pt_arithmetic.o" ]
then
  echo -n "For your information: Building \"bbrl_lib_fixed_pt_arithmetic.o\" ... "
  gcc -c -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/bbrl_lib_fixed_pt_arithmetic.c \
  -o $CTQG_PATH/bbrl_lib_fixed_pt_arithmetic.o  
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

if [ ! -e "$CTQG_PATH/bbrl__________memory_manager.o" ]
then
  echo -n "For your information: Building \"bbrl__________memory_manager.o\" ... "
  gcc -c -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/bbrl__________memory_manager.c \
  -o $CTQG_PATH/bbrl__________memory_manager.o  
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

if [ ! -e "$CTQG_PATH/bbrl________________________.o" ]
then
  echo -n "For your information: Building \"bbrl________________________.o\" ... "
  gcc -c -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/bbrl________________________.c \
  -o $CTQG_PATH/bbrl________________________.o  
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

if [ ! -e "$CTQG_PATH/bbrl________________sdll_sgt.o" ]
then
  echo -n "For your information: Building \"bbrl________________sdll_sgt.o\" ... "
  gcc -c -O2 -Wall -ansi -I $CTQG_PATH \
  $CTQG_PATH/bbrl________________sdll_sgt.c \
  -o $CTQG_PATH/bbrl________________sdll_sgt.o  
  if [ "$?" != "0" ]
  then
    exit 255
  fi
  echo Done.
fi

name=$1
no_ext_name=${name%.ctqg}
sim_name=./sim_$no_ext_name

# //(
#echo
#echo "            name = $name"
#echo "     no_ext_name = $no_ext_name"
#echo "        sim_name = $sim_name"
#echo
#read
# //)

# convert_to_bbrl $no_ext_name.ctqg
convert_to_bbrl $no_ext_name.ctqg

if [ "$?" != "0" ]
then
  exit 255
fi

gcc -O2 -std=c99 -I $CTQG_PATH -lm \
-include bbrl________________________.h \
-include bbrl_lib_fixed_pt_arithmetic.h \
-include bbrl__________ctqg_extension.c \
$CTQG_PATH/bbrl________________________.o \
$CTQG_PATH/bbrl_lib_fixed_pt_arithmetic.o \
$CTQG_PATH/bbrl__________memory_manager.o \
$CTQG_PATH/bbrl________________sdll_sgt.o \
$no_ext_name.c -o $sim_name

if [ "$?" != "0" ]
then
  exit 255
fi

$sim_name $no_ext_name.signals
if [ "$?" != "0" ]
then
  rm -f $sim_name
  exit 255
fi
    
$sim_name
if [ "$?" != "0" ]
then
  rm -f $sim_name
  rm -f $sim_name.gates
  rm -f $sim_name.ancilla
  exit 255
fi

mv $sim_name.gates $no_ext_name.gates
mv $sim_name.ancilla $no_ext_name.ancilla

# convert_to_qasm $no_ext_name.signals $no_ext_name.gates $no_ext_name.ancilla $no_ext_name.qasm
convert_to_qasm $no_ext_name.signals $no_ext_name.gates $no_ext_name.ancilla $no_ext_name.qasm

# //... rm -f $no_ext_name.c
rm -f $no_ext_name.ancilla
rm -f $no_ext_name.gates

echo "The sequence of gates is written to    \`$no_ext_name.qasm'."
echo "The list of i/o signals is written to  \`$no_ext_name.signals'."
echo "The simulator executable is written to \`sim_$no_ext_name'."
# echo Simulator usage:
# echo "\`sim_$no_ext_name <IN i/o signals with values file> <OUT file name>'."
echo
