#!/bin/bash

if [ ! -e $1 ]; then
    echo "File not found: $1"
    exit 1
fi

fname=`basename -s .scaffold ${1}`

SUFFIX=unknown
case $OSTYPE in
    darwin*)
        SUFFIX=dylib
        ;;
    linux*)
        SUFFIX=so
        ;;
esac

echo "Compiling ${1}..."
../build/Release+Asserts/bin/clang -c -emit-llvm -I/usr/include -I/usr/include/x86_64-linux-gnu -I/usr/lib/gcc/x86_64-linux-gnu/4.6/include ${1} -o ${fname}.ll

echo "Transforming cbits..."
../build/Release+Asserts/bin/opt -S -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -xform-cbit-stores ${fname}.ll -o ${fname}1.ll

echo "O1 optimizations..."

../build/Release+Asserts/bin/opt -S ${fname}1.ll -no-aa -tbaa -targetlibinfo -basicaa -o ${fname}1a.ll

../build/Release+Asserts/bin/opt -S ${fname}1a.ll -simplifycfg -domtree -o ${fname}1b.ll

../build/Release+Asserts/bin/opt -S ${fname}1b.ll -early-cse -lower-expect -o ${fname}2.ll

../build/Release+Asserts/bin/opt -S ${fname}2.ll -targetlibinfo -no-aa -tbaa -basicaa -globalopt -ipsccp -o ${fname}3.ll

../build/Release+Asserts/bin/opt -S ${fname}3.ll -instcombine -simplifycfg -basiccg -prune-eh -always-inline -functionattrs -domtree -early-cse -lazy-value-info -jump-threading -correlated-propagation -simplifycfg -instcombine -tailcallelim -simplifycfg -reassociate -domtree -loops -loop-simplify -lcssa -loop-rotate -licm -lcssa -loop-unswitch -instcombine -scalar-evolution -loop-simplify -lcssa -iv-users -indvars -loop-idiom -loop-deletion -loop-unroll -memdep -memcpyopt -sccp -instcombine -lazy-value-info -jump-threading -correlated-propagation -domtree -memdep -dse -adce -simplifycfg -instcombine -strip-dead-prototypes -preverify -domtree -verify -o ${fname}4.ll

echo "Unroll 1..."
../build/Release+Asserts/bin/opt -S ${fname}4.ll -mem2reg -loops -loop-simplify -loop-rotate -indvars -lcssa -loop-unswitch -loop-unroll -unroll-threshold=100000000 -sccp -simplifycfg -o ${fname}5.ll

echo "Unroll 2..."
../build/Release+Asserts/bin/opt -S ${fname}5.ll -mem2reg -loops -loop-simplify -loop-rotate -lcssa -loop-unroll -unroll-threshold=100000000 -sccp -simplifycfg -o ${fname}6.ll

echo "Unroll 3..."
../build/Release+Asserts/bin/opt -S ${fname}6.ll -mem2reg -loops -loop-simplify -loop-rotate -lcssa -loop-unroll -unroll-threshold=100000000 -sccp -simplifycfg -o ${fname}6.ll

echo "Unroll 4..."
../build/Release+Asserts/bin/opt -S ${fname}6.ll -mem2reg -loops -loop-simplify -loop-rotate -lcssa -loop-unroll -unroll-threshold=100000000 -sccp -simplifycfg -o ${fname}6.ll

echo "Function Cloning 1...."
../build/Release+Asserts/bin/opt -S -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -FunctionClone -sccp ${fname}6.ll -o ${fname}7.ll

echo "Unroll 5..."
../build/Release+Asserts/bin/opt -S ${fname}7.ll -mem2reg -loops -loop-simplify -loop-rotate -lcssa -loop-unroll -unroll-threshold=100000000 -o ${fname}8.ll

echo "Function Cloning 2..."
../build/Release+Asserts/bin/opt -S -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -FunctionClone -sccp ${fname}8.ll -o ${fname}9.ll

echo "Internalizing and Removing Unused Functions..."
../build/Release+Asserts/bin/opt -S ${fname}9.ll -internalize -globaldce -o ${fname}10.ll

echo "Gate Decomposition..."
../build/Release+Asserts/bin/opt -S -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -ToffoliReplace ${fname}10.ll -o ${fname}11.ll


echo "Dead Argument Elimination..."
../build/Release+Asserts/bin/opt -S -deadargelim ${fname}11.ll -o ${fname}12.ll


#echo "Generating ${fname}_res_count.log..."
#../build/Release+Asserts/bin/opt -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -ResourceCount ${fname}10.ll 2> ${fname}_res_count.log

echo "Generating ${fname}.qasm"
../build/Release+Asserts/bin/opt -load ../build/Release+Asserts/lib/Scaffold.${SUFFIX} -gen-qasm ${fname}12.ll 2> ${fname}.qasm

rm ${fname}.ll ${fname}1.ll ${fname}1a.ll ${fname}1b.ll ${fname}2.ll ${fname}3.ll ${fname}4.ll ${fname}5.ll ${fname}6.ll ${fname}7.ll ${fname}8.ll ${fname}9.ll ${fname}10.ll ${fname}11.ll 

