# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DDSynthesis.ui'
#
# Created: Fri Jun 10 18:05:14 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DDSynthesis(object):
    def setupUi(self, DDSynthesis):
        DDSynthesis.setObjectName(_fromUtf8("DDSynthesis"))
        DDSynthesis.resize(542, 300)
        DDSynthesis.setWindowTitle(_fromUtf8(""))
        self.verticalLayout_2 = QtGui.QVBoxLayout(DDSynthesis)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(DDSynthesis)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget(self.splitter)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout_2 = QtGui.QFormLayout(self.widget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.dd_type = QtGui.QComboBox(self.widget)
        self.dd_type.setObjectName(_fromUtf8("dd_type"))
        self.dd_type.addItem(_fromUtf8(""))
        self.dd_type.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dd_type)
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.formLayout = QtGui.QFormLayout(self.page)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.complemented = QtGui.QCheckBox(self.page)
        self.complemented.setChecked(True)
        self.complemented.setObjectName(_fromUtf8("complemented"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.complemented)
        self.label = QtGui.QLabel(self.page)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.reordering = QtGui.QComboBox(self.page)
        self.reordering.setObjectName(_fromUtf8("reordering"))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.reordering.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.reordering)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.page_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.default_decomposition = QtGui.QComboBox(self.page_2)
        self.default_decomposition.setObjectName(_fromUtf8("default_decomposition"))
        self.default_decomposition.addItem(_fromUtf8(""))
        self.default_decomposition.addItem(_fromUtf8(""))
        self.default_decomposition.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.default_decomposition)
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.kfdd_reordering = QtGui.QComboBox(self.page_2)
        self.kfdd_reordering.setObjectName(_fromUtf8("kfdd_reordering"))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.kfdd_reordering.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.kfdd_reordering)
        self.label_6 = QtGui.QLabel(self.page_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.sifting_factor = QtGui.QDoubleSpinBox(self.page_2)
        self.sifting_factor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sifting_factor.setDecimals(1)
        self.sifting_factor.setSingleStep(0.1)
        self.sifting_factor.setProperty(_fromUtf8("value"), 2.5)
        self.sifting_factor.setObjectName(_fromUtf8("sifting_factor"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.sifting_factor)
        self.label_7 = QtGui.QLabel(self.page_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_7)
        self.sifting_growth_limit = QtGui.QComboBox(self.page_2)
        self.sifting_growth_limit.setObjectName(_fromUtf8("sifting_growth_limit"))
        self.sifting_growth_limit.addItem(_fromUtf8(""))
        self.sifting_growth_limit.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.sifting_growth_limit)
        self.label_8 = QtGui.QLabel(self.page_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.sifting_method = QtGui.QComboBox(self.page_2)
        self.sifting_method.setObjectName(_fromUtf8("sifting_method"))
        self.sifting_method.addItem(_fromUtf8(""))
        self.sifting_method.addItem(_fromUtf8(""))
        self.sifting_method.addItem(_fromUtf8(""))
        self.sifting_method.addItem(_fromUtf8(""))
        self.sifting_method.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.sifting_method)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.runtime = QtGui.QLabel(self.widget)
        self.runtime.setText(_fromUtf8(""))
        self.runtime.setObjectName(_fromUtf8("runtime"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.runtime)
        self.draw_bdd = QtGui.QCheckBox(self.widget)
        self.draw_bdd.setObjectName(_fromUtf8("draw_bdd"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.draw_bdd)
        self.verticalLayout_2.addWidget(self.splitter)
        self.label.setBuddy(self.reordering)

        self.retranslateUi(DDSynthesis)
        self.stackedWidget.setCurrentIndex(0)
        self.reordering.setCurrentIndex(4)
        self.default_decomposition.setCurrentIndex(2)
        self.kfdd_reordering.setCurrentIndex(7)
        self.sifting_growth_limit.setCurrentIndex(1)
        self.sifting_method.setCurrentIndex(4)
        QtCore.QObject.connect(self.dd_type, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(DDSynthesis)
        DDSynthesis.setTabOrder(self.tabWidget, self.dd_type)
        DDSynthesis.setTabOrder(self.dd_type, self.complemented)
        DDSynthesis.setTabOrder(self.complemented, self.reordering)
        DDSynthesis.setTabOrder(self.reordering, self.draw_bdd)

    def retranslateUi(self, DDSynthesis):
        self.label_3.setText(QtGui.QApplication.translate("DDSynthesis", "Diagram Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.dd_type.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "Binary Decision Diagram (BDD)", None, QtGui.QApplication.UnicodeUTF8))
        self.dd_type.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Kronecker Functional Decision Diagram (KFDD)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DDSynthesis", "BDD Synthesis", None, QtGui.QApplication.UnicodeUTF8))
        self.complemented.setText(QtGui.QApplication.translate("DDSynthesis", "Complemented Edges", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DDSynthesis", "Reordering:", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "No Reordering", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Same", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(2, QtGui.QApplication.translate("DDSynthesis", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(3, QtGui.QApplication.translate("DDSynthesis", "Random Pivot", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(4, QtGui.QApplication.translate("DDSynthesis", "Sifting", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(5, QtGui.QApplication.translate("DDSynthesis", "Sifting Converge", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(6, QtGui.QApplication.translate("DDSynthesis", "Symmetric Sifting", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(7, QtGui.QApplication.translate("DDSynthesis", "Symmetric Sifting Converge", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(8, QtGui.QApplication.translate("DDSynthesis", "Group Sifting", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(9, QtGui.QApplication.translate("DDSynthesis", "Group Sifting Converge", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(10, QtGui.QApplication.translate("DDSynthesis", "Window (Size: 2)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(11, QtGui.QApplication.translate("DDSynthesis", "Window (Size: 3)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(12, QtGui.QApplication.translate("DDSynthesis", "Window (Size: 4)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(13, QtGui.QApplication.translate("DDSynthesis", "Window Converge (Size: 2)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(14, QtGui.QApplication.translate("DDSynthesis", "Window Converge (Size: 3)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(15, QtGui.QApplication.translate("DDSynthesis", "Window Converge (Size: 4)", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(16, QtGui.QApplication.translate("DDSynthesis", "Annealing", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(17, QtGui.QApplication.translate("DDSynthesis", "Genetic", None, QtGui.QApplication.UnicodeUTF8))
        self.reordering.setItemText(18, QtGui.QApplication.translate("DDSynthesis", "Exact", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DDSynthesis", "Default Decomposition:", None, QtGui.QApplication.UnicodeUTF8))
        self.default_decomposition.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "Shannon", None, QtGui.QApplication.UnicodeUTF8))
        self.default_decomposition.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Positive Davio", None, QtGui.QApplication.UnicodeUTF8))
        self.default_decomposition.setItemText(2, QtGui.QApplication.translate("DDSynthesis", "Negative Davio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DDSynthesis", "Reordering:", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "No Reordering", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Exact Friedman (DTL)", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(2, QtGui.QApplication.translate("DDSynthesis", "Exact Permutation (DTL)", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(3, QtGui.QApplication.translate("DDSynthesis", "Sifting (DTL)", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(4, QtGui.QApplication.translate("DDSynthesis", "Exact Friedman", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(5, QtGui.QApplication.translate("DDSynthesis", "Exact Permutation", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(6, QtGui.QApplication.translate("DDSynthesis", "Sifting", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(7, QtGui.QApplication.translate("DDSynthesis", "Sifting and DTL Sifting", None, QtGui.QApplication.UnicodeUTF8))
        self.kfdd_reordering.setItemText(8, QtGui.QApplication.translate("DDSynthesis", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DDSynthesis", "Sifting Factor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DDSynthesis", "Sifting Groth Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_growth_limit.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "Relative", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_growth_limit.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Absolute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("DDSynthesis", "Sifting Method:", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_method.setItemText(0, QtGui.QApplication.translate("DDSynthesis", "Random", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_method.setItemText(1, QtGui.QApplication.translate("DDSynthesis", "Initial", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_method.setItemText(2, QtGui.QApplication.translate("DDSynthesis", "Greatest", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_method.setItemText(3, QtGui.QApplication.translate("DDSynthesis", "Loser First", None, QtGui.QApplication.UnicodeUTF8))
        self.sifting_method.setItemText(4, QtGui.QApplication.translate("DDSynthesis", "Verify", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DDSynthesis", "Run-time:", None, QtGui.QApplication.UnicodeUTF8))
        self.draw_bdd.setText(QtGui.QApplication.translate("DDSynthesis", "Draw DD", None, QtGui.QApplication.UnicodeUTF8))

