# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PatternInput.ui'
#
# Created: Tue Feb 15 18:07:22 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PatternInput(object):
    def setupUi(self, PatternInput):
        PatternInput.setObjectName(_fromUtf8("PatternInput"))
        PatternInput.resize(554, 425)
        self.verticalLayout_3 = QtGui.QVBoxLayout(PatternInput)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget = QtGui.QWidget(PatternInput)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.openButton = QtGui.QToolButton(self.widget)
        self.openButton.setText(_fromUtf8(""))
        self.openButton.setAutoRaise(True)
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.horizontalLayout.addWidget(self.openButton)
        spacerItem = QtGui.QSpacerItem(515, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.widget)
        self.splitter = QtGui.QSplitter(PatternInput)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.stateTable = QtGui.QTableWidget(self.groupBox)
        self.stateTable.setObjectName(_fromUtf8("stateTable"))
        self.stateTable.setColumnCount(2)
        self.stateTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.stateTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.stateTable)
        self.widget_2 = QtGui.QWidget(self.groupBox)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addState = QtGui.QToolButton(self.widget_2)
        self.addState.setText(_fromUtf8(""))
        self.addState.setAutoRaise(True)
        self.addState.setObjectName(_fromUtf8("addState"))
        self.verticalLayout.addWidget(self.addState)
        self.removeState = QtGui.QToolButton(self.widget_2)
        self.removeState.setEnabled(False)
        self.removeState.setText(_fromUtf8(""))
        self.removeState.setAutoRaise(True)
        self.removeState.setObjectName(_fromUtf8("removeState"))
        self.verticalLayout.addWidget(self.removeState)
        spacerItem1 = QtGui.QSpacerItem(20, 100, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sequencesTable = QtGui.QTableWidget(self.groupBox_2)
        self.sequencesTable.setObjectName(_fromUtf8("sequencesTable"))
        self.sequencesTable.setColumnCount(0)
        self.sequencesTable.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.sequencesTable)
        self.widget_3 = QtGui.QWidget(self.groupBox_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.addSequence = QtGui.QToolButton(self.widget_3)
        self.addSequence.setEnabled(False)
        self.addSequence.setText(_fromUtf8(""))
        self.addSequence.setAutoRaise(True)
        self.addSequence.setObjectName(_fromUtf8("addSequence"))
        self.verticalLayout_2.addWidget(self.addSequence)
        self.removeSequence = QtGui.QToolButton(self.widget_3)
        self.removeSequence.setEnabled(False)
        self.removeSequence.setText(_fromUtf8(""))
        self.removeSequence.setAutoRaise(True)
        self.removeSequence.setObjectName(_fromUtf8("removeSequence"))
        self.verticalLayout_2.addWidget(self.removeSequence)
        spacerItem2 = QtGui.QSpacerItem(20, 108, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_3.addWidget(self.widget_3)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(PatternInput)
        QtCore.QMetaObject.connectSlotsByName(PatternInput)

    def retranslateUi(self, PatternInput):
        PatternInput.setWindowTitle(QtGui.QApplication.translate("PatternInput", "PatternInput", None, QtGui.QApplication.UnicodeUTF8))
        self.openButton.setToolTip(QtGui.QApplication.translate("PatternInput", "Load pattern from file", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PatternInput", "Sequential States", None, QtGui.QApplication.UnicodeUTF8))
        self.stateTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("PatternInput", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.stateTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("PatternInput", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.addState.setToolTip(QtGui.QApplication.translate("PatternInput", "Add state", None, QtGui.QApplication.UnicodeUTF8))
        self.removeState.setToolTip(QtGui.QApplication.translate("PatternInput", "Remove state", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("PatternInput", "Input Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.addSequence.setToolTip(QtGui.QApplication.translate("PatternInput", "Add sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.removeSequence.setToolTip(QtGui.QApplication.translate("PatternInput", "Remove sequence", None, QtGui.QApplication.UnicodeUTF8))

